config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, only: [:create, :index, :show, :new] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  root to: "lists#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list_id, scope: :movie_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end


  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie to a list:</h1>

<div>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <%= simple_form_for list do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add list", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="banner">
  <div>
    <h1>Welcome to the site!</h1>
    <h5>Your favorite movies everywhere</h5>
    <p><%= link_to "All lists", lists_path, id: "all_lists", class: "btn btn-primary" %></p>
    <p><%= link_to "Create new list", new_list_path, id: "new_list", class: "btn btn-primary" %></p>
  </div>
</div>

<h1>All lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
    </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<div class="banner">
  <div>
    <h1>Welcome to the site!</h1>
    <h5>Your favorite movies everywhere</h5>
    <p><%= link_to "All lists", lists_path, id: "all_lists", class: "btn btn-primary" %></p>
    <p><%= link_to "Create new list", new_list_path, id: "new_list", class: "btn btn-primary" %></p>
  </div>
</div>

<h1>Add a list to our database:</h1>

<%= render "form", list: @list, id: "form" %>

app/views/lists/show.html.erb
<div class="banner">
  <div>
    <h1>Welcome to the site!</h1>
    <h5>Your favorite movies everywhere</h5>
    <p><%= link_to "All lists", lists_path, id: "all_lists", class: "btn btn-primary" %></p>
    <p><%= link_to "Create new list", new_list_path, id: "new_list", class: "btn btn-primary" %></p>
  </div>
</div>

<h2> List: </h2>

<h3><%= @list.name %></h3>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item">
      <%= bookmark.movie.title %>, comment: <%= bookmark.comment %>
      <%= link_to "Delete movie",  list_bookmark_path(@list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Delete?"} %>
    </li>
  <% end %>
</ul>
<p><%= link_to "Add a movie to this list",  new_list_bookmark_path(@list), class: "btn btn-primary" %></p>